# Generated by Django 4.1.2 on 2022-10-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brands",
            fields=[
                ("brand_id", models.AutoField(primary_key=True, serialize=False)),
                ("brand_name", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Cars",
            fields=[
                ("car_id", models.AutoField(primary_key=True, serialize=False)),
                ("brand_name", models.CharField(max_length=20)),
                ("car_name", models.CharField(max_length=20)),
                ("engine_type", models.CharField(max_length=20)),
                ("transmission", models.CharField(max_length=20)),
                ("purchase_date", models.DateField()),
                ("photo_file_name", models.CharField(max_length=100)),
            ],
        ),
    ]
